apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.backend.service.name }}
spec:
  selector:    
    app: backend-label
  type: NodePort
  ports: 
  - name: http
    port: 3030
    targetPort: 3030
    nodePort: 30036
    protocol: TCP
