apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-label
  template:
    metadata:
      labels:
        app: backend-label
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.container.Image }}
        ports:
        - name: tcp
          containerPort: 3030
        env:
        - name: NODE_ENV
          value: {{ .Values.backend.container.NODE_ENV | quote }}
        - name: VERSION
          value: {{ .Values.backend.container.VERSION | quote }}
        - name: TYPEORM_CONNECTION
          value: {{ .Values.backend.container.TYPEORM_CONNECTION | quote }}
        - name: TYPEORM_MIGRATIONS_DIR
          value: {{ .Values.backend.container.TYPEORM_MIGRATIONS_DIR | quote }}
        - name: TYPEORM_ENTITIES
          value: {{ .Values.backend.container.TYPEORM_ENTITIES | quote }}
        - name: TYPEORM_MIGRATIONS
          value: {{ .Values.backend.container.TYPEORM_MIGRATIONS | quote }}
        - name: TYPEORM_HOST
          value: {{ .Values.database.service | quote }}
        - name: TYPEORM_PORT
          value: {{ .Values.backend.container.TYPEORM_PORT | quote }}
        - name: TYPEORM_USERNAME
          value: {{ .Values.backend.container.TYPEORM_USERNAME | quote }}
        - name: TYPEORM_PASSWORD
          value: {{ .Values.backend.container.TYPEORM_PASSWORD | quote }}
        - name: TYPEORM_DATABASE
          value: {{ .Values.backend.container.TYPEORM_DATABASE | quote }}
