jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env:
      DOCKER_REPOSITORY: bashox
      FRONTEND_IMAGE_NAME: revolgy-frontend
      BACKEND_IMAGE_NAME: revolgy-frontend
      IMAGE_TAG: ${{ github.run_number }} # ${{ github.sha }}
      # AKS_RESOURCE_GROUP: rg-aks-cluster-tf-023
      # EKS_NAME: aks-cluster 
      # ACR_NAME: acrforakstf023
      # TERRAFORM_VERSION: 1.1.9
      # WORKING_DIRECTORY: infra

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}
